@baseUrl = https://pirioe4xbg.execute-api.ap-southeast-2.amazonaws.com
@contentType = application/json

###

GET {{baseUrl}}/products HTTP/1.1
Content-Type: {{contentType}}


###
GET {{baseUrl}}/products/3 HTTP/1.1
Content-Type: {{contentType}}

